Repository grey-software/toonin, pull requests merged in 2019-12, with the labels that each got.

#107 Heroku docker
  .circleci/config.yml
  .circleci/setup-heroku.sh
  .dockerignore
  Dockerfile
  deployment/package.json
  deployment/server.js
  deployment/vars.js
  package-lock.json
  package.json
Labels: release

#112 Titlefix
  backend/index.js
  client-redesign/src/components/roomName.vue
  deployment/server.js
  extension/src/js/background/index.js
Labels: bug

#114 Added easy markers to change io host during local dev
  client-redesign/src/assets/app.js
  client-redesign/src/main.js
  extension/src/js/background/index.js
Labels: cleanup

#118 Video streaming
  client-redesign/src/components/ConnectToRoom.vue
  client-redesign/src/components/PlayerControls.vue
  client-redesign/src/components/VideoPlayer.vue
  client-redesign/src/store/index.js
  client-redesign/src/views/Home.vue
  extension/src/HomeView.vue
  extension/src/app.js
  extension/src/js/background/index.js
Labels: enhancement

#119 Renamed client-redesign to client
  .circleci/config.yml
  .gitignore
  Dockerfile
  client-redesign/src/components/connection.vue
  client-redesign/src/components/title.vue
  client/README.md
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/server.js
  client/src/App.vue
  client/src/assets/favicon.ico
  client/src/assets/icon.png
  client/src/assets/icon40.png
  client/src/components/ConnectToRoom.vue
  client/src/components/Connection.vue
  client/src/components/PlayerControls.vue
  client/src/components/Title.vue
  client/src/components/TooninIcon.vue
  client/src/components/VideoPlayer.vue
  client/src/main.js
  client/src/plugins/vuetify.js
  client/src/router/index.js
  client/src/store/index.js
  client/src/views/Home.vue
  deployment/server.js
  setup.sh
Labels: cleanup
